name: Generate recipes

on:
    workflow_dispatch:

    schedule:
        - cron:  '30 4 * * SAT'

jobs:
    generateRecipes:
        runs-on: ubuntu-latest
        timeout-minutes: 30

        steps:
            # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
            - name: Checkout
              uses: actions/checkout@v4
              with:
                fetch-depth: 0

            - name: Generate recipes
              run: |
                for file in $( find $GITHUB_WORKSPACE -name generateMissingRecipes.sh ); do 
                    echo
                    echo ==========================
                    echo === $( date '+%Y%m%d-%H%M%S' ) - $file
                    bash $file
                done

                git status
              env:
                GITHUB_WORKSPACE: ${{ github.workspace }}

            # # FOR TEST
            - name: FAIL
              run: exit 1

            ##############################################################
            ### Commit and push
            ##############################################################
            - name: Commit and push
              run: |
                # Git config commit user
                git config --local user.email "action@github.com"
                git config --local user.name "GitHub Action"
                git config pull.rebase true

                bash $GITHUB_WORKSPACE/githubScripts/push-release.sh $LEVAIN_VERSION
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
